name: run

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "Cargo.*"
      - "**/*.rs"
      - ".github/workflows/*.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install
        run: cargo install --quiet --path .
      - name: Run with defaults
        run: |
          for file in examples/*.sh; do bash "$file"; echo ""; done
      - name: Run with changed style
        run: |
          for file in examples/*.sh; do bash "$file" --style psql --left-pad 2 --right-pad 2; echo ""; done
